### ISSUE TITLE
improving .fennelrc + cli

### ISSUE THREAD

**Issue by jaawerth** [bakpakin/Fennel#193]
Right now, `.fennelrc` doesn't allow you to do some things you'd want to do in an rc file, such as modifying `fennel.path`. Here I'm proposing a few improvements.

## TODOs

When invoking fennelrc,

- [x] add a CLI flag (perhaps `-u` or `-C` ?) to load a custom init file in lieu of `.fennelrc`, or to not load one at all
- [x] set both the `options` and `fennel` itself on the `env` so `fennel.path` and other things can be manipulated from the RC file
- [ ] when launching a repl from the CLI, pass some kind of mode/context flag to `.fennelrc` so it can differentiate repl usage vs running or compiling
- [ ] have the CLI use `.fennelrc` in every context in which it's invoked (or at least for execution - compiling is more debatable), rather than only in the repl

## Exploration/possible todos 
- Allow the use of `XDG_CONFIG_HOME` (see [XDG base directory specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)) to allow other places to check for the init file, configurable via non-fennel-specific env vars, before falling back to `.fennelrc`

**Comment by jaawerth** [comment]
In addition to the above, I've also been mulling this over, but I'm interested in whether people think this is overkill.

## possible changes to where `.fennelrc` is sourced

Right now it just looks in `$HOME/.fennelrc` by default. We may want to consider having it follow XDG behaviors, looking in `${XDG_CONFIG_HOME:-$HOME/.config/fennel/fennelrc}` before falling back to `$HOME/.fennelrc`.

It's also worth considering having it look for the file in the project root and scanning upwards, so project-specific fennelrc files can be used, but that might be going too far into territory better covered by a separate, more complex CLI tool than we want for the base lang. E.g. `fnl` tool ala clojure's [clj](https://clojure.org/guides/deps_and_cli).

**Comment by technomancy** [comment]
I like all of these suggestions except the last one; I feel pretty strongly that project-specific stuff should not be included in Fennel itself without a lot more consideration.

For the first one, maybe a better flag would be to skip the loading of `.fennelrc` altogether instead of providing a different path?

**Comment by jaawerth** [comment]
I figured project-specific stuff would be a no-go, but what about XDG? It's a common standard, and would save us having to introduce new args or fennel-specific env vars that increase cognitive debt. Failing that, maybe a flag to disable and one to override, or a flag that can do both like `vim -u path/to/vimrc` and `vim -u NONE`?

I just think it's a good practice, if you're going to implement an rc-file, to also provide ways to both ignore it or use a different one without having to mess with your file system.

**Comment by technomancy** [comment]
Oh yeah, when I suggested the flag for skipping `.fennelrc` I was thinking we had another arg for "load this file before proceeding" but we don't, so yeah, a flag to replace seems better.

XDG location sounds fine; I don't have strong feelings about it, as long as ~/.fennelrc continues to work.

**Comment by jaawerth** [comment]
Thanks for the feedback! Editing the OP and adding this to `0.4.0`

**Comment by turbo** [comment]
I'd also add a way to choose the lua interpreter using the rcfile.

**Comment by jaawerth** [comment]
Nice! I know we want to limit the scope of the CLI per earlier discussion, but I think @turbo's suggestion is worth adding to the list.

A lot of folks primarily use fennel with luajit, and right now one would need to manually invoke luajit on the `fennel` cli executable to do so. That isn't the end of the world, but being able to configure it in a cross-platform way without having to set an alias or [wrapper script](https://gist.github.com/jaawerth/a97c785e1637dba2459dd2b2eea3e42d) would be nice.

**Comment by technomancy** [comment]
> I'd also add a way to choose the lua interpreter using the rcfile.

I don't think this should be in scope for the rcfile; by the time the rcfile is read, the lua executable has already been chosen, so it is too late to change it. This should be selected by modifying your `$PATH` instead, (or by means of `update-alternatives`) which is already a well-understood and well-supported method. Having one fennel process which launches a second Lua makes things a lot more complicated for a benefit that's largely redundant.

**Comment by technomancy** [comment]
> have the CLI use .fennelrc in every context in which it's invoked (or at least for execution - compiling is more debatable), rather than only in the repl

I really don't think this is a good idea. It can be nice to have some helper functions like tab completion or your favorite pretty-printer in the repl, but outside the repl this seems like it's just asking for non-reproducible behavior. Everything that affects a project's running or tests should be part of the project codebase, not the user dotfiles.

**Comment by technomancy** [comment]
> add a CLI flag (perhaps -u or -C ?) to load a custom init file in lieu of .fennelrc, or to not load one at all

I addressed this by adding a `--load` flag in 6133b422092340ff55a84aba4842f60869c94c8b but it doesn't interact with the `.fennelrc` file at all.

**Comment by jaawerth** [comment]
> > have the CLI use .fennelrc in every context in which it's invoked (or at least for execution - compiling is more debatable), rather than only in the repl
> 
> I really don't think this is a good idea. It can be nice to have some helper functions like tab completion or your favorite pretty-printer in the repl, but outside the repl this seems like it's just asking for non-reproducible behavior. Everything that affects a project's running or tests should be part of the project codebase, not the user dotfiles.

Yeah, that makes sense. That kinda thing can be better addressed in some kind of wrapper tool.

> > add a CLI flag (perhaps -u or -C ?) to load a custom init file in lieu of .fennelrc, or to not load one at all
> 
> I addressed this by adding a `--load` flag in [6133b42](https://github.com/bakpakin/Fennel/commit/6133b422092340ff55a84aba4842f60869c94c8b) but it doesn't interact with the `.fennelrc` file at all.

If, as established above, `.fennelrc` is only sourced when running a REPL from the CLI, I think we're probably good to go so long as we throw in a flag to ignore `.fennelrc`, since that'll allow for a total override with any kind of wrapper shell script or tool.

**Comment by technomancy** [comment]
Reopening this because the XDG bits aren't quite right.

**Comment by technomancy** [comment]
I think #207 takes care of this now.
